env:
  global:
    DOCKER_COMPOSE_VERSION: 1.9.0
  matrix:
    - TEST_SUITE=nonfunctional
    - TEST_SUITE=functional BROWSER="firefox:latest:Windows 2012"
    - TEST_SUITE=functional BROWSER="safari:8.0:OS X 10.10"
    - TEST_SUITE=functional BROWSER="internet explorer:11.0:Windows 7"
sudo: required
language: python
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - openssl aes-256-cbc -K $encrypted_ef2af4a5c304_key -iv $encrypted_ef2af4a5c304_iv -in google-credentials.json.enc -out google-credentials.json -d
install:
  - docker pull ebmdatalab/openprescribing-base:latest
  - docker pull mdillon/postgis:latest
cache:
  directories:
    - docker
services:
  - docker
script:
  - export SAUCE_HOST=$(ip -4 addr show scope global dev docker0 | grep inet | awk '{print $2}' | cut -d / -f 1)
  - docker-compose run --service-ports test && docker-compose run --service-ports test-production
notifications:
  email:
    - tech@ebmdatalab.net
  slack:
    secure: ECNcYBYWt4emYm9Br88Ts9VRxHGe3IkMjLk/MTKAaqY3lJPmC7vy+d1+YazBufxPNAIbR/1OdxJGcxsnj+zpYoCgLVOF9sxWaOf6x9dL2bTquU+lUIzUVDb+VilRgnlqv9BHZQlcYUFsODQTqQhxeJ73pUpVxYsdXWuSs5CGgJMsJMJ6IQAgiLBStC/8dNCXFFQPGptjdA1xqeCG47lnLK0zwzlaWJobrqga50NqlL4xfjMnVXq+AohGq5HtmrOt4cy6HkX3zKuHR0GZs6j/hWA6wbIbGeO5d/4hGT0CaiROlK1trketyvec8z69MqjsQJrK0Au1KYF7VOhJjLykseFiTK4IdluLipn3rVX9JRjBAegrrMEy/Cpjgc8nJqo3WAYoaPL7SY+jl8vwzeL+Tg8JdKLp9L/2eELkLeqfaugqLPCkACkcVyZ5oKhUMdiK1WYyLsPzGu44lpCZ0DuXnpZLQ+AVC1EK9JAVfYC8mUCFzaIftT6g2MlaafevpXHQ3T0+CPfoQ58fQE7T6eoQpWYqlkFaV+cjb1n/1+qKCGGqJmSadZt3umADqF3vri46+HKO/BhNOxmAxPwcAdJ89qkvp5N5x7ZKBPm3KAiRNbB0nfiF+DWXMxFy01Ibfuc2Uoclk1h63ML8AgBdAUhqsmK3hI6xTcPA76QWRK9uYqU=
addons:
  sauce_connect:
    username: ebmdatalab
    access_key:
      secure: MlmeHStJ91/CHGiz2wVo8rOsrBjk181DbQPSV4PYlJQyogDuGQrKy8LIkUZlzaXUhhG+H5jdUyfoBGJXhZCCxjwzf4yibZEYpHWvWGfCwb8g4SFr9doDSxmwY0aJgYkJGAMPKxz7MQ4LXgNp/6z+NO1kw3uU0poNQEMz73Do9rd6iVRvjRThj4q0wGv5AoV3+LshVtHKHBpcEs0ZyHzmEuGrpEuR0Ak4g1Dif0HoMmAepmU/pNui18tMHx3HDtBerKuo1+ou4eEtxBUy4OVnAas7+zgw3e1pWawsf3mMTSKGxY6rFTIE5A5N+Te589vVGucpc0XzfoxpFtn13DLMFG4Mf0mdBgHYBo+fCuIrBwPZ0RoD7NV7RfhKKGQ4rpLP6uwjFTCtbG1CyT5+zz/RxxbE+guqmIUZI6oZZQsXx7mk2cypQgV3La41O85VJ6Y74QRCK9c59ChiDxjfYbIMLysP8E4d5GmLnLUFlGjSTr9G8bP3kHZqhE12tg2JPqhMG3eMvQngQfQhgXqh4shBPOJCUthinafJizyJ9lscx0OMmNkb4GMqXAEJNIz7Xp0xFJvsOnLyoWO3rJ2UoZd1tNuv4OnhQOsZvvHePueAyYateXPHsFPOaIhgoAQkGkALI+E8+2dSWUVZo5EqYd00beM4Ni6GTThpZ3tIIfTu2+w=
