---
USER: vagrant
HOME: "/home/{{ USER }}"
virtualenv_path: /code/openprescribing/venv
project_root_path: /code/openprescribing/openprescribing
requirements_path: /code/openprescribing/requirements.txt
db_user: dev
db_password: sdkjasdalskdax
db_name: openprescribing_dev
log_path: /code/openprescribing/logs
secret_key: sdjfhasiufqpiasln
envvars:
  - var: DB_NAME
    name: DB_NAME
    content: "{{ db_name }}"
  - var: DB_USER
    name: DB_USER
    content: "{{ db_user }}"
  - var: DB_PASS
    name: DB_PASS
    content: "{{ db_password }}"
  - var: SECRET_KEY
    name: SECRET_KEY
    content: "{{ secret_key }}"
  - var: GMAIL_PASS
    name: GMAIL_PASS
    content: test
  - var: MAILGUN_WEBHOOK_USER
    name: MAILGUN_WEBHOOK_USER
    content: test
  - var: MAILGUN_WEBHOOK_PASS
    name: MAILGUN_WEBHOOK_PASS
    content: test
