---
USER: vagrant
HOME: "/home/{{ USER }}"
db_user: dev
db_password: sdkjasdalskdax
db_name: openprescribing_dev
secret_key: sdjfhasiufqpiasln
repo_root: /openprescribing
virtualenv_path: "{{ repo_root }}/venv"
apps_root: "{{ repo_root }}/openprescribing"
requirements_path: "{{ repo_root }}/requirements.txt"
log_path: "{{ repo_root }}/logs"

envvars:
  - var: DB_NAME
    name: DB_NAME
    content: "{{ db_name }}"
  - var: DB_USER
    name: DB_USER
    content: "{{ db_user }}"
  - var: DB_PASS
    name: DB_PASS
    content: "{{ db_password }}"
  - var: DB_HOST
    name: DB_HOST
    content: "localhost"
  - var: SECRET_KEY
    name: SECRET_KEY
    content: "{{ secret_key }}"
